### ISSUE TITLE
macOS command does not install prerequisites

### ISSUE THREAD

**Issue by Human7900** [uup-dump/converter#10]
macOS command does not install prerequisites. This is the error.
`==> Searching for similarly named formulae...
Error: No similarly named formulae found.
Error: No available formula or cask with the name "cabextract".
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.`.
EDIT: Seems to be a problem with Brew, fixed now. However, there is another error while running `uup_download_macos.sh`
`Retrieving aria2 script...
/Users/myusername/Downloads/22000/uup_download_macos.sh: line 52: aria2c: command not found
Failed to retrieve aria2 script`.

**Comment by raspiduino** [comment]
You should install `aria2`. Try `brew install aria2`
