### ISSUE TITLE
Converter fails at "Exporting Windows 10 core to install.wim"

### ISSUE THREAD

**Issue by Sweattings** [uup-dump/converter#17]
Im Trying to get the Windows 10 arm Insider Preview, downloadet everything. But im getinng this error, if someone could help me that would be so nice. :)

```
Exporting Windows 10 Core to install.wim...
[ERROR] Can't open "/Users/agerdes/Desktop/21390-3//*.esd" read-only: No such file or directory
ERROR: Exiting with error code 47:
       Failed to open a file.
Failed to export Windows 10 Core to install.wim
```

**Comment by abbodi1406** [comment]
Are you using it manually? or via uup_download script?
try to pass the uups_directory path without ending `/`

**Comment by TheJags** [comment]
hi @abbodi1406

I'm having the same exact issue with build 22468 and 22471. I just logged into GitHub to file an issue. I have tried 2 times on 2 different Ubuntu machines, both for build 22468 and 22471.

I am running script from `uupdump.net` where `uup converter version is 0.6.4`. 

> try to pass the uups_directory path without ending /

How do I pass the path you've mentioned please.

Many thanks.

The errors I'm getting:
````
Build 22471 error:

Exporting Windows 10 Professional to install.wim...

[ERROR] "/Windows/WinSxS/wow64_microsoft-windows-wsp-health_31bf3856ad364e35_10.0.22471.1000_none_248874d2ca823b9e/wsp_health.mof": blob not found
        SHA-1 message digest of missing blob:
        ef1b5591c1d00fd3e317af7521fab921cf3b367e

ERROR: If this is a delta WIM, use the --ref argument to specify the WIM(s) on which it is based.

ERROR: Exiting with error code 55:
       A file resource needed to complete the operation was missing from the WIM.

Failed to export Windows 10 Professional to install.wim
````

````
Build 22468 error:

Exporting Windows 10 Professional to install.wim...

[ERROR] "/Windows/WinSxS/amd64_microsoft-windows-m..simple-provider-dll_31bf3856ad364e35_10.0.22468.1000_none_553fffe06dafa0f1/msdaosp.dll": blob not found
        SHA-1 message digest of missing blob:
        84d544605a48fdaf818390cf10507acdeb649865

ERROR: If this is a delta WIM, use the --ref argument to specify the WIM(s) on which it is based.

ERROR: Exiting with error code 55:
       A file resource needed to complete the operation was missing from the WIM.

Failed to export Windows 10 Professional to install.wim
````

**Comment by TheJags** [comment]
The only reference I could find for `uups_directory` is in line #264 in `convert.sh`:

````
echo "$0 [compression] [uups_directory] [create_virtual_editions]"
````

And I have no idea on how to pass the path that you have mentioned. Thanks a lot.

**Comment by Sweattings** [comment]
Thanks for the answers, I fixed it. But to be Honest I have no idea how. I changed my shell to "zsh" and reinstalled homebrew. And after that, it worked without any errors. So I guess this issue can be closed. But Thanks for the quick responses. 👍

**Comment by TheJags** [comment]
@abbodi1406 sorry to bother you. I still need help please.

As I do not have or want `zsh`.

Could you please elaborate what you meant by:

> try to pass the uups_directory path without ending /

Thanks a lot.

**Comment by TheJags** [comment]
Well I tried assigning full path to `UUPs`:

````
/home/ubuntu/w11/22471/files/convert.sh wim /home/ubuntu/w11/22471/UUPs
````

but getting the same error:

````
Exporting Windows 10 Professional to install.wim...

[ERROR] "/Windows/WinSxS/wow64_microsoft-windows-wsp-health_31bf3856ad364e35_10.0.22471.1000_none_248874d2ca823b9e/wsp_health.mof": blob not found
        SHA-1 message digest of missing blob:
        ef1b5591c1d00fd3e317af7521fab921cf3b367e

ERROR: If this is a delta WIM, use the --ref argument to specify the WIM(s) on which it is based.

ERROR: Exiting with error code 55:
       A file resource needed to complete the operation was missing from the WIM.

Failed to export Windows 10 Professional to install.wim
````

**Comment by TheJags** [comment]
> > Well I tried assigning full path to `UUPs` directory:
> > ```
> > /home/ubuntu/w11/22471/files/convert.sh wim /home/ubuntu/w11/22471/UUPs
> > ```
> 
> change location to `/home/ubuntu/w11/22471/` then run `./files/convert.sh wim UUPs 0`
> 
> if you still get errors, it mean the converter might need some fixing

Thanks for the reply. 

And yes, I think converter needs fixing as I have got the same error with the command you suggested:

````
Exporting Windows 10 Professional to install.wim...

[ERROR] "/Windows/WinSxS/wow64_microsoft-windows-wsp-health_31bf3856ad364e35_10.0.22471.1000_none_248874d2ca823b9e/wsp_health.mof": blob not found

        SHA-1 message digest of missing blob:
        ef1b5591c1d00fd3e317af7521fab921cf3b367e

ERROR: If this is a delta WIM, use the --ref argument to specify the WIM(s) on which it is based.

ERROR: Exiting with error code 55:
      
A file resource needed to complete the operation was missing from the WIM.
Failed to export Windows 10 Professional to install.wim

ubuntu@instance-20210917-2008:~/w11/22471$
````

**Comment by unkn0wnUlv** [comment]
I was getting this error too.

`[ERROR] "/Windows/WinSxS/wow64_microsoft-windows-wsp-health_31bf3856ad364e35_10.0.22471.1000_none_248874d2ca823b9e/wsp_health.mof": blob not found

        SHA-1 message digest of missing blob:
        ef1b5591c1d00fd3e317af7521fab921cf3b367e

ERROR: If this is a delta WIM, use the --ref argument to specify the WIM(s) on which it is based.

ERROR: Exiting with error code 55:
      
A file resource needed to complete the operation was missing from the WIM.
Failed to export Windows 10 Professional to install.wim`

I literally wasted one night trying to fix this, but I fixed the next morning, first try, with the following steps:

- Rebooted my M1 MBA;
- Downloaded the Latest Public Release build arm64 (the pro version, that comes with the converter, including updates and component cleanup);
- Ran the converter as I normally would and voila!

**Comment by adislice** [comment]
I'm also having the same problem on Linux. 
I tried to download the Windows 11 build 22471 x64 using the downloader script from uupdump.net and got this error:

```
Exporting Windows 10 Professional to install.wim...
[ERROR] "/Windows/WinSxS/wow64_microsoft-windows-wsp-health_31bf3856ad364e35_10.0.22471.1000_none_248874d2ca823b9e/wsp_health.mof": blob not found
        SHA-1 message digest of missing blob:
        ef1b5591c1d00fd3e317af7521fab921cf3b367e
ERROR: If this is a delta WIM, use the --ref argument to specify the WIM(s) on which it is based.
ERROR: Exiting with error code 55:
       A file resource needed to complete the operation was missing from the WIM.
Failed to export Windows 10 Professional to install.wim
```

**Comment by zunpiau** [comment]
> Could you try v0.6.5? thanks

I tried to download the  Windows 10  21H2 (19044.1266) amd64, Windows Pro Edition with Linux convert. v0.6.5 and v0.6.4 has same problem: 
```
[ERROR] "/Windows/WinSxS/amd64_microsoft-windows-c..riencehost.appxmain_31bf3856ad364e35_10.0.19041.1_none_b8a98655ecfd7c6a/retailDemoSetup.js": blob not found
        SHA-1 message digest of missing blob:
        13de3f41ac91edf26cda62476655f10910859629
ERROR: If this is a delta WIM, use the --ref argument to specify the WIM(s) on which it is based.
ERROR: Exiting with error code 55:
       A file resource needed to complete the operation was missing from the WIM.
```

**Comment by linan7788626** [comment]
Hi guys, 

Do you happen to have any updates on this issue?
I am using UUDP converter 0.6.6 on Mac OS Big Sur 11.5.2, and I got similar errors

```
Exporting Windows 11 Core to install.wim...
[ERROR] "/Windows/WinSxS/arm64_microsoft-windows-playtoreceiver-dll_31bf3856ad364e35_10.0.22471.1000_none_a9ca7adfad0a1471/PlayToReceiver.dll": blob not found
        SHA-1 message digest of missing blob:
        0790459623c51d55a1a0910e561dd2042e1ee4cd
ERROR: If this is a delta WIM, use the --ref argument to specify the WIM(s) on which it is based.
ERROR: Exiting with error code 55:
       A file resource needed to complete the operation was missing from the WIM.
Failed to export Windows 11 Core to install.wim
```

Any comments or suggestions are highly appreciated. 

Thank you so much!

All the best,
Nan

**Comment by Hazmi35** [comment]
Have the same problems here

**Comment by abbodi1406** [comment]
Could you test this attached one? it should create two debug log
[convert.zip](https://github.com/uup-dump/converter/files/7375664/convert.zip)
s

**Comment by Qemics** [comment]
`./convert.sh 
UUP Converter v0.6.7
Note: This script does not and cannot support the integration of updates.
Use the Windows version of the converter to integrate updates.

CAB -> ESD: Microsoft-Windows-WordPad-FoD-Package~31bf3856ad364e35~amd64~~_73f98a7e
CAB -> ESD: Microsoft-Windows-LanguageFeatures-Basic-en-us-Package~31bf3856ad364e35~amd64~~_553f9964
CAB -> ESD: Microsoft-Windows-StepsRecorder-Package~31bf3856ad364e35~amd64~~_079b54fe
CAB -> ESD: Microsoft-Windows-InternetExplorer-Optional-Package~31bf3856ad364e35~amd64~~_3a44e27a
CAB -> ESD: Microsoft-Windows-Printing-WFS-FoD-Package~31bf3856ad364e35~amd64~~_7d1db7d4
CAB -> ESD: Microsoft-Windows-LanguageFeatures-OCR-en-us-Package~31bf3856ad364e35~amd64~~_fac6477a
CAB -> ESD: Microsoft-Windows-LanguageFeatures-Speech-en-us-Package~31bf3856ad364e35~amd64~~_baba93d3
CAB -> ESD: Microsoft-Windows-UserExperience-Desktop-Package~31bf3856ad364e35~amd64~~_3ea6c17a
CAB -> ESD: Microsoft-Windows-LanguageFeatures-TextToSpeech-en-us-Package~31bf3856ad364e35~amd64~~_534ac81a
CAB -> ESD: Microsoft-Windows-Hello-Face-Package~31bf3856ad364e35~amd64~~_14ae581f
CAB -> ESD: Microsoft-Windows-PowerShell-ISE-FOD-Package~31bf3856ad364e35~amd64~~_8da96965
CAB -> ESD: Microsoft-Windows-MediaPlayer-Package~31bf3856ad364e35~amd64~~_e1706f9d
CAB -> ESD: Microsoft-Windows-Hello-Face-Migration-Package~31bf3856ad364e35~amd64~~_a6d01b85
CAB -> ESD: Microsoft-OneCore-DirectX-Database-FOD-Package~31bf3856ad364e35~amd64~~_017ec2cf
CAB -> ESD: Microsoft-Windows-Notepad-FoD-Package~31bf3856ad364e35~amd64~~_281d2fa7
CAB -> ESD: OpenSSH-Client-Package~31bf3856ad364e35~amd64~~_2854d6b2
CAB -> ESD: Microsoft-Windows-QuickAssist-Package~31bf3856ad364e35~amd64~~_3c2ffb0d
CAB -> ESD: Microsoft-OneCore-ApplicationModel-Sync-Desktop-FOD-Package~31bf3856ad364e35~amd64~~_daa92c0d
CAB -> ESD: Microsoft-Windows-LanguageFeatures-Handwriting-en-us-Package~31bf3856ad364e35~amd64~~_514f1cef
CAB -> ESD: Microsoft-Windows-TabletPCMath-Package~31bf3856ad364e35~amd64~~_107597c5
CAB -> ESD: Microsoft-Windows-MSPaint-FoD-Package~31bf3856ad364e35~amd64~~_785ad658

Creating ISO structure...
Applying image 1 ("Windows Setup Media") from "/home/minh/Downloads/uup/UUPs/core_en-us_c54adad7.esd" to directory "ISODIR"
Extracting file data: 264 MiB of 264 MiB (100%) done
Done applying WIM image.

Exporting winre.wim...
Using LZX compression with 12 threads
Archiving file data: 971 MiB of 971 MiB (100%) done

Creating boot.wim...
[WARNING] Ignoring extended attributes of 1 files
          (use --unix-data mode to extract these)
"ISODIR/sources/boot.wim" original size: 392554 KiB
Using LZX compression with 12 threads
Archiving file data: 1040 MiB of 1040 MiB (100%) done
"ISODIR/sources/boot.wim" optimized size: 386782 KiB
Space saved: 5771 KiB

Exporting Windows 10 Core to install.wim...
[ERROR] "/Windows/WinSxS/wow64_microsoft-windows-advapi32res_31bf3856ad364e35_10.0.19041.1_none_b2414eccf462d7fe/advapi32res.dll": blob not found
        SHA-1 message digest of missing blob:
        505fb000950d469ac57f208948061850732f933f
ERROR: If this is a delta WIM, use the --ref argument to specify the WIM(s) on which it is based.
ERROR: Exiting with error code 55:
       A file resource needed to complete the operation was missing from the WIM.
Failed to export Windows 10 Core to install.wim`
