### ISSUE TITLE
Disable Reserved Storage (for both this & the Windows Converter)

### ISSUE THREAD

**Issue by ImportTaste** [uup-dump/converter#21]
There exists a setting that forces Windows to reserve 10GB of space for system maintenance, documented here: https://techcommunity.microsoft.com/t5/storage-at-microsoft/windows-10-and-reserved-storage/ba-p/428327

<ins>**While this can be accomplished through setupcomplete.cmd, it won't take effect until a Windows Update is applied.**</ins>

_While offline pre-modding of the registry hive is an option_, it's substantially more time-consuming compared to the alternative –  <ins>**DISM received a new command line option to disable it**</ins>: `/Set-ReservedStorageState /State:Disabled` 
_([Documentation of this option located here](https://docs.microsoft.com/en-us/windows-hardware/manufacture/desktop/dism-storage-reserve?view=windows-11))_

However, if the multi-platform converter can't get access to that same luxury, pre-modding the registry hive is the only option. If you want to go that route, here is the exact registry key that needs to be changed (in .reg format):
```reg
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\ReserveManager]
"ShippedWithReserves"=dword:00000000
```

**Comment by RealEnthousiast** [comment]
Why should it be a component of the converter, when using a setupcomplete.cmd or offline pre-modding the registry hive of the mounted wim will instantly apply the setting at install.

**Comment by ImportTaste** [comment]
> Why should it be a component of the converter, when using a setupcomplete.cmd

As mentioned, this wouldn't work until a Windows update is applied.

> offline pre-modding the registry hive of the mounted wim will instantly apply the setting at install.

The DISM option makes it so that offline pre-modding the registry hive is unnecessary. I'm not sure if the multi-platform converter will have access to that same option, though.

**Comment by abbodi1406** [comment]
It's a personal preference, should not be forced to all users (i.e. some may want that feature)

however, Windows Converter could have an option to disable it during update integration process
