### ISSUE TITLE
[suggestion] make MountUUP W10UIuup folder name unique

### ISSUE THREAD

**Issue by eladkarako** [uup-dump/converter#25]
`MountUUP` `W10UIuup` folders shares the name for both W10 and W11 build actions,  
which prevents running W10 build and W11 build process in parallel.  
`MountUUP10`+`UIuup10`, `MountUUP11`+`UIuup11` would allow such parallel action.  

this still means no two W10 build actions can be done in parallel,  
since those actions would either fail to mount or unmount the folder,  
or overwrite files.

making a short, but unique suffix to the folder names,  
at the start of the build session would make it possible to build more than one ISO at once, which is more time efficient. suffix can be as short as the current minute and seconds for the current time, it is sufficiently different.

all the batch files and dism and imagex are already capable of handling multiple input and outputs by their nature.

**Comment by abbodi1406** [comment]
Maybe randomize suffix like W10UI.cmd?
```
set "_mount=!_mount!_%random%"
if exist "!_mount!\" set "_mount=!_mount!_%random%"
set "_cabdir=!_cabdir!_%random%"
if exist "!_cabdir!\" set "_cabdir=!_cabdir!_%random%"
```

**Comment by eladkarako** [comment]
sure, why not.

**Comment by abbodi1406** [comment]
What scripts? virtual and multi_arch?

**Comment by eladkarako** [comment]
afaik `convert-UUP.cmd` handles most of the actions that uses those two folders.  
just thought it is a good idea to keep a reference to the working folders in-case you'll ever want to spread the functionality over few files.  
that aside, it is best to keep the folder name under 12 characters (8+3),  
that leaves maybe 2-3 characters, that short - random might be insufficient (I.E. repeating) for  that, number of seconds or milliseconds in the current time might work better  
cmd `for /f "tokens=3-4 delims=/:." %%a in ("%TIME%") do ( echo "%%a%%b" )`  
powershell `((Get-Date).millisecond)`)  

<img src="https://user-images.githubusercontent.com/415238/183901708-697c8ca4-0e5a-4883-b5aa-e73166325695.png">
<img src="https://user-images.githubusercontent.com/415238/183901718-a8d26c88-34f0-480d-8e0a-2080b1e475a4.png">

**Comment by abbodi1406** [comment]
Could test this with parallel actions or so?
[convert-UUP84.zip](https://github.com/uup-dump/converter/files/9332837/convert-UUP84.zip)

**Comment by eladkarako** [comment]
> The thing is, some users would want the static folder names, so they could exclude them in Anti-virus to speed up the conversion/updating using randomation will prevent that
> 
> we could make the randomized folders as sub-directories under MountUUP/W10UIuup folders but in that case, the parent folder will be left (empty) after the script finish

in this case,  
either lets settle down on just two variations,  
`MountUUP10`+`UIuup10` for W10, and `MountUUP11`+`UIuup11` for W11.  

or use the randomness/time-based suffix,  
but instead of placing the folder directly under the same drive,  
first create a folder named `uupdump`, and place everything in it.  

```txt
D:/
|-- /uudump
|   |-- /MountUUP666
|   |-- /UIuup666
```

this way users will be able to add to the ignore list `/uudump` and "whatever" sub-folders it may have would be automatically be ignored as well.

<hr/>

or possibly with this naming scheme...

```txt
D:/
|-- /uup
|   |-- /uup_mnt_10_666
|   |-- /uup_cab_10_666
```

**Comment by abbodi1406** [comment]
Directories are set before processing UUP files, differentiation isn't feasible

why short names are important? you are not exactly working on Windows XP :)

like i said, parent folder concept is good, but it would be left empty afterwards (to avoid confliction with other sessions)

**Comment by eladkarako** [comment]
> Directories are set before processing UUP files, differentiation isn't feasible

explained above already.  
generate the name early, write it to a text file in the project folder,  
read its content at the start of every script that needs to use the folder name,  
either mount or cab file storage/extraction.  
and this way you can share the date across multiple scripts.
(I think there is just one script that actually handles it all though).

> why short names are important? you are not exactly working on Windows XP :)

whitespace 100% breaks stuff,  
short('ish) names are just good practice.  
as long as you use `_` instead of ` `, cmd and dism should be fine I guess..

> parent folder .. left empty afterwards

1. project self clean first (remove mount, ui).
2. after deleting mount and ui folders, check to see if there are other folders there.
3. if there are no other folders: you are the last project to finish, also delete `uup`.
4. if there are folders, let them worry about that, do nothing, quit.
5. safe. since you delete the folders only in the last step in your script.

**Comment by abbodi1406** [comment]
Did you try convert-UUP84 above?
