### ISSUE TITLE
[MacOS] genisoimage nor mkisofs does seem to be installed

### ISSUE THREAD

**Issue by Arcovegle** [uup-dump/converter#30]
When I am downloading Windows 11 Preview iso using your shell script '_uup_download_macos.sh_', this bug occurs. I have installed  '_cabextract wimlib cdrtools chntpw_' with _homebrew_ and '_mkisofs_' can be found with 'which' command.

The problem is, your shell script, in line 28-34.
```shell
for prog in genisoimage mkisofs; do
  which $prog &>/dev/null && break;

  echo "genisoimage nor mkisofs does seem to be installed"
  echo "Check the readme.unix.md for details"
  exit 1
done
```

The 'for loop' here is a misuse since if I have installed one of _genisoimage_ and _mkisofs_ but not both of them, it just **EXIT**. This problem can also be found in '_convert.sh_'.

It is a simple mistake but hope you can fix it :)

**Comment by eraseyourknees** [comment]
>MacOS

Nobody here owns a Mac or anything resembling it.

>Windows 11 Preview

Don't even bother using this script, you'll waste your time and get a half-broken image. Windows 11 newer than 21H2 requires being created on Windows.

>since if I have installed one of genisoimage and mkisofs but not both of them

The issue is different. It works if you have genisoimage only, but not when you have mkisofs only.

**Comment by Arcovegle** [comment]
> Nobody here owns a Mac or anything resembling it.
> 
To tell you the truth, I have a M1 Macbook Air and it is really nice~
> 
> Don't even bother using this script, you'll waste your time and get a half-broken image. Windows 11 newer than 21H2 requires being created on Windows.
> 
I don't think this is a waste of time because I get a full image of Windows 11 Insider Preview 25201.1000 and successfully run Windows 11 on both VMware Fusion and UTM. If you also have a Mac, you can give it a try.
> 
> The issue is different. It works if you have genisoimage only, but not when you have mkisofs only.
>
That's true. Anyway, glad to see that you have fixed it.
