### ISSUE TITLE
Failed to extract Microsoft-Windows-LanguageFeatures-Speech-en-us-Package-arm64.cab

### ISSUE THREAD

**Issue by ammar-faifi** [uup-dump/converter#39]
I'm using iMac M1 I tried different UUP dumps and still get the following error

```
Status Legend:
(OK):download completed.

UUP Converter v0.7.2
Note: This script does not and cannot support the integration of updates.
Use the Windows version of the converter to integrate updates.

CAB -> ESD: Microsoft-Windows-LanguageFeatures-Speech-en-us-Package-arm64
Failed to extract Microsoft-Windows-LanguageFeatures-Speech-en-us-Package-arm64.cab
```

it's an issue to all UUPs files not for this specific one

**Comment by ammar-faifi** [comment]
Moreover I modified the following line 
https://github.com/uup-dump/converter/blob/590a19f6de78b0125eb37d1cd944d47115d6d094/convert.sh#L426
to see the output and it seems the issue from `cabextract`

```
UUPs/Microsoft-Windows-LanguageFeatures-Speech-en-us-Package-arm64.cab: WARNING; possible 8648 extra bytes at end of file.
Extracting cabinet: UUPs/Microsoft-Windows-LanguageFeatures-Speech-en-us-Package-arm64.cab
  extracting temp/$filehashes$.dat
  extracting temp/arm64.arm_microsoft-windows-l..rm64.arm-deployment_31bf3856ad364e35_10.0.22000.1_none_613c7c373b2203c2.manifest
  extracting temp/arm64.arm_microsoft-windows-s..zer-en-us-n-onecore_31bf3856ad364e35_10.0.22000.1_none_b1eab346b8e3b1b4/DictationCommands.0409.grxml
temp/arm64.arm_microsoft-windows-s..zer-en-us-n-onecore_31bf3856ad364e35_10.0.22000.1_none_b1eab346b8e3b1b4/DictationCommands.0409.grxml: No such file or directory
  extracting temp/arm64.arm_microsoft-windows-s..zer-en-us-n-onecore_31bf3856ad364e35_10.0.22000.1_none_b1eab346b8e3b1b4/SpellingGrammar.0409.grxml
temp/arm64.arm_microsoft-windows-s..zer-en-us-n-onecore_31bf3856ad364e35_10.0.22000.1_none_b1eab346b8e3b1b4/SpellingGrammar.0409.grxml: No such file or directory
  extracting temp/arm64.arm_microsoft-windows-s..zer-en-us-n-onecore_31bf3856ad364e35_10.0.22000.1_none_b1eab346b8e3b1b4/Tokens_SR_en-US-N.xml
temp/arm64.arm_microsoft-windows-s..zer-en-us-n-onecore_31bf3856ad364e35_10.0.22000.1_none_b1eab346b8e3b1b4/Tokens_SR_en-US-N.xml: No such file or directory
  extracting temp/arm64.arm_microsoft-windows-s..zer-en-us-n-onecore_31bf3856ad364e35_10.0.22000.1_none_b1eab346b8e3b1b4/VES-Disambiguation.0409.grxml
temp/arm64.arm_microsoft-windows-s..zer-en-us-n-onecore_31bf3856ad364e35_10.0.22000.1_none_b1eab346b8e3b1b4/VES-Disambiguation.0409.grxml: No such file or directory
  extracting temp/arm64.arm_microsoft-windows-s..zer-en-us-n-onecore_31bf3856ad364e35_10.0.22000.1_none_b1eab346b8e3b1b4/VES-SeeItSayIt.0409.grxml
temp/arm64.arm_microsoft-windows-s..zer-en-us-n-onecore_31bf3856ad364e35_10.0.22000.1_none_b1eab346b8e3b1b4/VES-SeeItSayIt.0409.grxml: No such file or directory
  extracting temp/arm64.arm_microsoft-windows-s..zer-en-us-n-onecore_31bf3856ad364e35_10.0.22000.1_none_b1eab346b8e3b1b4/VES-Select.0409.grxml
temp/arm64.arm_microsoft-windows-s..zer-en-us-n-onecore_31bf3856ad364e35_10.0.22000.1_none_b1eab346b8e3b1b4/VES-Select.0409.grxml: No such file or directory
```
not all the logs

**Comment by lesydimitri** [comment]
This seems to have something to do with new defaults introduced in cabextract 1.10: https://www.cabextract.org.uk/#changes

"cabextract now overwrites symlinks by default, both directories and files. This is to be consistent with other archive tools. This does not affect symlinks that are part of the --directory option"


Adding the "-k" flag to cabextract in convert.sh seems to solve the issue.

**Comment by ammar-faifi** [comment]
@lesydimitri I tried this in a separate command as well as modifying the `convert.sh` and it worked !

not sure if this has any unwanted side effects

**Comment by SpookyUmi** [comment]
Doesn't work for me, it seems that I can't modify the convert.sh file. I tried adding the -k flag in it at the right line `cabextract -d "$extractDir" "$file" >/dev/null 2>/dev/null`  but it gets removed each time I run the UUP.

**Comment by ammar-faifi** [comment]
> Doesn't work for me, it seems that I can't modify the convert.sh file. I tried adding the -k flag in it at the right line `cabextract -d "$extractDir" "$file" >/dev/null 2>/dev/null`  but it gets removed each time I run the UUP.

Because the script `uup_download_....` overwrites the `convert.sh`,

So you should modify it after running the download script then just run the convert script directly as
```shell
./files/convert.sh
```

**Comment by gitjoob** [comment]
Still fails for me even after removing the downloading converters and adding -k to convert.sh

CAB -> ESD: Microsoft-Windows-LanguageFeatures-Speech-en-us-Package-arm64
Failed to extract Microsoft-Windows-LanguageFeatures-Speech-en-us-Package-arm64.cab

**Comment by alfredcc** [comment]
Still fails

**Comment by ammar-faifi** [comment]
let me make sure you get right

1- run `./uup_download_macos.sh`
2- adding the option `-k`
3- run `./files/convert.sh`

you might not add `-k` in good order so it didn't take effect, it should be like this
`cabextract -k -d "$extractDir" "$file" >/dev/null 2>/dev/null`

**Comment by gitjoob** [comment]
> 

Yeah something must have gone wrong when I had -k in the wrong place, Removed all and retried the fix and then it worked. Thanks!

**Comment by visualjazz-sbrunno** [comment]
> @gitjoob
> 
> let me make sure you get it right
> 
> 1 - run `./uup_download_macos.sh` 2 - adding the option `-k` 3 - run `./files/convert.sh`
> 
> you might not add `-k` in good order so it didn't take effect, it should be like this `cabextract -k -d "$extractDir" "$file" >/dev/null 2>/dev/null`

this worked for me finally! Thanks heaps mate

**Comment by SamSlainte** [comment]
Can anyone tell me how to change "$extractDir" and "$file" parts?
> cabextract -k -d "$extractDir" "$file" >/dev/null 2>/dev/null
(I'm so beginner at github and comandline...)

**Comment by SamSlainte** [comment]
I got it!

1.  `vi ./files/convert.sh`
2.  find the line `cabextract -d "$extractDir" "$file" >/dev/null 2>/dev/null`
3. add "-k" in i mode
4. saved the file and run the convert.sh file

**Comment by rob3rt6** [comment]
> @gitjoob
> 
> let me make sure you get it right
> 
> 1 - run `./uup_download_macos.sh` 2 - adding the option `-k` 3 - run `./files/convert.sh`
> 
> you might not add `-k` in good order so it didn't take effect, it should be like this `cabextract -k -d "$extractDir" "$file" >/dev/null 2>/dev/null`


> @gitjoob
> 
> let me make sure you get it right
> 
> 1 - run `./uup_download_macos.sh` 2 - adding the option `-k` 3 - run `./files/convert.sh`
> 
> you might not add `-k` in good order so it didn't take effect, it should be like this `cabextract -k -d "$extractDir" "$file" >/dev/null 2>/dev/null`

When running ./convert.sh
I get **Specified directory containing UUP files does not exist!**

**Comment by rob3rt6** [comment]
@ammar-faifi When running ./convert.sh I get "Specified directory containing UUP files does not exist!" ?

**Comment by Err0r-v2** [comment]
You have to go back with cd ../ and then run from your location

**Comment by fancyham** [comment]
This is what I did:

1.  run ./uup_download_macos.sh which will eventually give a cabextract error
2. edit /files/convert.sh 
3. add the option -k to cabextract: 
change: cabextract -d "$extractDir" "$file" >/dev/null 2>/dev/null 
to: cabextract -k -d "$extractDir" "$file" >/dev/null 2>/dev/null
4.  run ./files/convert.sh

Note that step 1 overwrites convert.sh, so you need to edit convert.sh after step 1 has completed

**Comment by DaveFlashNL** [comment]
yup seems to work now, but it will not build an iso on macos for me: 

```
UUP Converter v0.7.2
Note: This script does not and cannot support the integration of updates.
Use the Windows version of the converter to integrate updates.
```

how do i built an iso now?
