### ISSUE TITLE
Converter don't apply (all) updates on Linux

### ISSUE THREAD

**Issue by runapp** [uup-dump/converter#7]
I've tried uupdump on 19H2 (18363.1316) recently, and found that the final ISO is of 19H1 (with filename `18362.1_MULTI_X64_EN-US.ISO`), meanwhile the windows version just gets the correct result (`18363.1316.210109-2207.19H2_RELEASE_SVC_PROD1_CLIENTMULTI_X64FRE_EN-US.ISO`).
I'm still struggling on sort out the call relation among all those batch subroutines. To my limited knowledge, the update that changes image from 18362 to 18363 is depolied with `dism`. Is that the key problem of doing the same on linux? Or the key might be some magic in `convert-UUP.cmd` that has hard coded 18362->18363?

**Comment by luzeagithub** [comment]
from the README:
> For obvious reasons this script will never support integration of Cumulative Updates to created images.

You must have a Windows host OS to create an ISO with integrated updates, so the filename is right, because it never integrated those updates. Use Windows in a VM instead.

**Comment by runapp** [comment]
Sorry I've missed README.md in this repository.
