### ISSUE TITLE
Consider looking for chntpw in /usr/sbin

### ISSUE THREAD

**Issue by davidebeatrici** [uup-dump/converter#8]
The official Debian package (https://packages.debian.org/buster/chntpw) installs the binary in `/usr/sbin`.

As a result, if the script is not run as `root` the commands that make use of the tool fail to execute.

The workaround is to explicitly add `/usr/sbin` to `PATH` before running the converter:
```bash
export PATH=${PATH}:/usr/sbin
```

**Comment by luzeagithub** [comment]
Fixed, thanks.

**Comment by davidebeatrici** [comment]
Thanks for implementing the fix!
